### ISSUE TITLE
Keybinding conflict: Ctrl-K

### ISSUE THREAD

**Issue by ytang** [Tehnix/spaceneovim-layers#38]
Ctrl-K is used both in `+nav/text` and in `+completion/snippets`. Since both layers are enabled by default in `vimrc.sample.vim`, it would be ideal to avoid any conflict.

**Comment by Tehnix** [comment]
I seriously need a system to detect overlapping keys :/ (although a bit harder with regular mappings.)

My original intention was for it to be Alt-[jk], but on macOS that didn't work, so I went for Ctrl-Shift-[jk], but shift is apparently never sent to terminal emulators.

I fixed the Alt issue though, on mac you have to send the underlying key, which is `∆` for alt-k and `‹` for alt-j. Hopefully this will be somewhat consistent across keyboard layouts, since it's not the number/symbol keys which quite often are mapped differently.
