### ISSUE TITLE
+lang/rust undefined variable g:sp_format_on_save

### ISSUE THREAD

**Issue by soratobukuroneko** [Tehnix/spaceneovim-layers#60]
On a fresh install when I enable +lang/rust layer I get the following error:
```
Error detected while processing /home/andrea/.config/nvim/spaceneovim-layers/layers/+lang/rust/config.vim:                                                     
line   23:                                                                                                                                                     
E121: Undefined variable: g:sp_format_on_save                                                                                                                  
E15: Invalid expression: g:sp_format_on_save                                                                                                                   
"main.rs" 3L, 45C                                                                                                                                              
E121: Undefined variable: g:sp_format_on_save
```

**Comment by Tehnix** [comment]
Hmm, this might be because the variable is only set up in the `+tools/format` layer. Could you try adding `Layer '+nav/buffers'` to your configuration (above the rust layer) and see if it works?

If that's the case, then we'd to have this 

https://github.com/Tehnix/spaceneovim-layers/blob/master/layers/%2Btools/format/config.vim#L1 

in the language layers that use this as well, so one isn't forced to have the format layer as well :)

**Comment by samusz** [comment]
Had the same error for Rust, ruby and others... 
Added the _tools/format_ layer as described and the error was gone. 
Thanks

**Comment by Tehnix** [comment]
I was quick on closing it 😅
